apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: proshop-monitoring
spec:
  selector:
    app: grafana
  ports:
    - port: 3000       
      targetPort: 3000
      nodePort: 32000  
  type: NodePort
