version: "3.2"

services:
  mongo:
    container_name: mongo 
    image: mongo:4.4
    #enviroment:
    ports:
      - "27017:27017"
    networks:
      - proshop_mern_app
    volumes:
      - myvolume:/data/db
    restart: always
  
  backend:
     build: ./backend
     environment:
       - NODE_ENV= production
       - PORT=5000
       - MONGO_URI=mongodb://mongo:27017/proshop
       - JWT_SECRET=abc123
     # - PAYPAL_CLIENT_ID=your_paypal_client_id
     ports:
       - "5000:5000"  
     networks:
       - proshop_mern_app
     depends_on:
       - mongo
     restart: always
  
  frontend:
     build: ./frontend
     environment:
       - SKIP_PREFLIGHT_CHECK=true
     ports:
       - "3000:3000"
     networks:
       - proshop_mern_app
     depends_on:
       - backend
     restart: always   
       

volumes:
  myvolume:

networks:
  proshop_mern_app:
    driver: bridge

