apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: proshop-frontend-app
  namespace: proshop
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: proshop-frontend
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
